// This file was autogenerated by closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../../galactica/galactica-angular/character_card.js', ['galactica.card'], ['goog.dom']);
goog.addDependency('../../../../galactica/galactica-angular/character_card_db.js', ['galactica.characterDb'], []);
goog.addDependency('../../../../galactica/galactica-angular/character_deck.js', ['galactica.deck'], ['galactica.card']);
goog.addDependency('../../../../galactica/galactica-angular/controller.js', ['galactica.controller'], ['galactica.characterDb', 'galactica.deck', 'galactica.loyaltyDeck']);
goog.addDependency('../../../../galactica/galactica-angular/galactica.js', ['galactica.start', 'galactica.ui'], ['galactica.controller', 'galactica.deck', 'goog.dom', 'goog.events', 'goog.ui.Checkbox', 'goog.ui.Zippy']);
goog.addDependency('../../../../galactica/galactica-angular/gamecontroller.js', ['galactica.gameController'], []);
goog.addDependency('../../../../galactica/galactica-angular/gameui.js', ['galactica.gameInterface'], ['goog.dom']);
goog.addDependency('../../../../galactica/galactica-angular/loyalty_deck.js', ['galactica.loyaltyDeck'], []);
